zenodo/zenodo-migrator

- .editorconfig
- setup.py
- tests/test_zenodo_migrationkit.py
- zenodo_migrationkit/__init__.py
- zenodo_migrationkit/cli.py
- zenodo_migrationkit/ext.py
- zenodo_migrationkit/tasks.py
* Adds CLI + celery tasks to load dump of Zenodo.
> cli: dump loader

- setup.py
- tests/dump.json
- tests/test_task.py
- tests/test_zenodo_migrationkit.py
- zenodo_migrationkit/cli.py
- zenodo_migrationkit/tasks.py
- zenodo_migrationkit/transform.py
> global: migration script improvements

- .travis.yml
- requirements-devel.txt
- setup.py
- tests/test_zenodo_migrationkit.py
- zenodo_migrationkit/cli.py
- zenodo_migrationkit/tasks.py
- zenodo_migrationkit/transform.py
* Fixes issues with migration after testing the transformations on
a larger dataset.
* Adds command for easier testing of the record transformations.
> transform: record migration fixes

- zenodo_migrationkit/transform.py
> transform: no notification

- zenodo_migrationkit/cli.py
- zenodo_migrationkit/transform.py
> transform: filename to key renaming

- requirements-devel.txt
- setup.py
- tests/conftest.py
- tests/data/deposit.json
- tests/test_deposits_transform.py
- zenodo_migrationkit/cli.py
- zenodo_migrationkit/deposit_transform.py
- zenodo_migrationkit/tasks.py
* Adds legacy migration for deposit.
> global: deposit migration

- docs/conf.py
- requirements-devel.txt
- setup.py
- tests/conftest.py
- tests/test_deposits_transform.py
- zenodo_migrationkit/deposit_transform.py
> installation: zenodo dependency removal

- zenodo_migrationkit/cli.py
- zenodo_migrationkit/transform.py
* Fixes issue with record schema update.
> records: data model changes

- zenodo_migrationkit/transform.py
> transform: thesis field fix

- zenodo_migrationkit/transform.py
> transform: migrate license

- scripts/jsondumper.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
> scripts: fix print

- scripts/load.sh
- scripts/reindex.sh
- scripts/setup_load_env.sh
- setup.py
- tests/test_github.py
- zenodo_migrator/cli.py
- zenodo_migrator/github.py
- zenodo_migrator/serializers/schemas/dump.py
- zenodo_migrator/tasks.py
* Deposit migraiton fixes.
* Adds extra CLI dump/load bash functions for raw SQL.
> deposit: minor deposit migration fixes

- scripts/preload.sh
- scripts/reindex.sh
- setup.py
- zenodo_migrator/deposit.py
- zenodo_migrator/serializers/schemas/dump.py
> deposit: migration fixes

- zenodo_migrator/cli.py
- zenodo_migrator/deposit.py
- zenodo_migrator/tasks.py
> deposit: more migration fixes

- zenodo_migrator/tasks.py
> deposit: unregistered PID error handling during migration

- zenodo_migrator/cli.py
> github: releases migration bugfix

- setup.py
- zenodo_migrator/cli.py
- zenodo_migrator/legacy/pids.py
> pid: DOI dumping and migration

- zenodo_migrator/cli.py
- zenodo_migrator/tasks.py
> oaiserver: oaiserver ID update CLI

- zenodo_migrator/cli.py
- zenodo_migrator/tasks.py
Needs handling of the case, where one record has a concept doi and unit tests.
> versioning: CLI for linking records together

- zenodo_migrator/cli.py
- zenodo_migrator/tasks.py
> global: SIPFiles reconstruction cli

- zenodo_migrator/tasks.py
> sips: addition of sipfiles re-creation for externallyy changed files
